webtalk_init -webtalk_dir G:/Shared drives/EECE 351 Labs/Project/SecondMilestone/ARM_Multi_Cycle/ARM_Multi_Cycle.sim/sim_1/behav/xsim/xsim.dir/Test_ARM_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec  3 21:41:57 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "46b87e78-2c01-4aae-bbbf-5e4fd825bae5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "48917b80d4b54e589ddc2756e1eca9da" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9700_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3401704952 -regid "" -xml G:/Shared drives/EECE 351 Labs/Project/SecondMilestone/ARM_Multi_Cycle/ARM_Multi_Cycle.sim/sim_1/behav/xsim/xsim.dir/Test_ARM_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/Shared drives/EECE 351 Labs/Project/SecondMilestone/ARM_Multi_Cycle/ARM_Multi_Cycle.sim/sim_1/behav/xsim/xsim.dir/Test_ARM_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/Shared drives/EECE 351 Labs/Project/SecondMilestone/ARM_Multi_Cycle/ARM_Multi_Cycle.sim/sim_1/behav/xsim/xsim.dir/Test_ARM_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
